services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=security_jpa"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
